apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-cluster
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: my-app-cluster
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: my-app-cluster
subjects:
- kind: ServiceAccount
  name: my-app-cluster
  namespace: default
roleRef:
  kind: ClusterRole
  name: my-app-cluster
  apiGroup: rbac.authorization.k8s.io
