apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: alpine
spec:
  serviceAccountName: my-app
  containers:
  - name: alpine
    image: alpine
    command:
      - sleep
      - "86400"
    imagePullPolicy: IfNotPresent
    
