apiVersion: v1
kind: Pod
metadata:
  name: pripod
spec:
  serviceAccountName: pripod-serviceaccount
  containers:
    - name: pripod
      image: guitarrapc/pripod.sample:0.1
      command: ["sleep", "86400"]
