---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pripod-role
  annotations:
    app.kubernetes.io/type: role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pripod-rolebinding
  annotations:
    app.kubernetes.io/type: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pripod-role
subjects:
  - kind: ServiceAccount
    name: pripod-serviceaccount
