apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: php-redis
      image: k8s.gcr.io/guestbook:v3
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 2000m
          memory: 1000Mi
      env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
      ports:
        - name: http-server
          containerPort: 3000
