# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: .*/development/secrets/.*.yaml
    kms: "arn:aws:kms:REAGION:ACCOUNT_ID:key/ARN"
  - path_regex: .*/staging/secrets/secrets\.enc\.yaml$
    kms: "arn:aws:kms:REAGION:ACCOUNT_ID:key/ARN"
