# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: .*/development/secrets/.*
    kms: "arn:aws:kms:REAGION:ACCOUNT_ID:key/ARN"
  - path_regex: .*/staging/secrets/.*
    kms: "arn:aws:kms:REAGION:ACCOUNT_ID:key/ARN"
