resources:
  - namespace.yaml

configMapGenerator:
  - name: grafana-dashboard-kubernetes
    files:
      - ./kubernetes-cluster-overview.json
      - ./kubernetes-deployment-statefulset-daemonset-metrics.json
      - ./kubernetes-status.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
