apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment

spec:
  replicas: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10%

  selector:
    matchLabels:
      app: photo-view

  template:
    metadata:
      labels:
        app: photo-view
    spec:
      containers:
      - image: sampleguitarrapcacr.azurecr.io/photo-view:v1.0
        name: photoview-container
        ports:
        - containerPort: 80
