apiVersion: v1
kind: Service
metadata:
  name: greet-grpc-svc
spec:
  type: LoadBalancer
  selector:
    app: greet-grpc
  ports:
  - name: greet
    protocol: TCP
    port: 50051
    targetPort: 50051
    