apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:5.0.7-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  type: LoadBalancer
  selector:
    app: redisinsight
  ports:
    - port: 8001
      targetPort: redisinsight
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  selector:
    matchLabels:
      app: redisinsight
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight
          imagePullPolicy: Always
          env:
            # require to set HOST/PORT on env to avoid pod port conflict when using svc.
            # ref: https://github.com/RedisLabs/redislabs-docs/issues/676
            - name: REDISINSIGHT_HOST
              value: "0.0.0.0"
            - name: REDISINSIGHT_PORT
              value: "8001"
          ports:
            - containerPort: 8001
              name: redisinsight
